dist: xenial
language: generic
sudo: required
go:
  - stable
services:
  - docker
env:
  - BUILD_ARCH=arm32v7
  - BUILD_ARCH=arm64v8
before_install:
  - sudo apt update -y && sudo apt install --only-upgrade docker-ce -y
  - docker info
install:
  - 'echo ''{ "experimental": true }'' | sudo tee /etc/docker/daemon.json'
  - sudo systemctl restart docker
  - sudo apt-get --yes --no-install-recommends install qemu-user-static
before_script:
  - sudo ./prepare-qemu
  - umask
  - ls -la rootfs
script:
  - ./build
after_success:
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./push'

jobs:
  include:
    - stage: deploy
      name: "Create Manifest"
      install: 'mkdir $HOME/.docker/ && echo ''{ "experimental": "enabled" }'' > $HOME/.docker/config.json'
      before_script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      script: ./create-manifest
