dist: xenial
language: generic
sudo: required
go:
  - stable
services:
  - docker
env:
  - BUILD_ARCH=arm32v7
  - BUILD_ARCH=arm64v8
install:
  - go get github.com/estesp/manifest-tool
  - 'echo ''{ "experimental": true }'' | sudo tee /etc/docker/daemon.json'
  - sudo systemctl restart docker
  - sudo apt-get --yes --no-install-recommends install qemu-user-static
before_script:
  - sudo ./prepare-qemu
script:
  - ./build
after_success:
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./push'

jobs:
  include:
    - stage: deploy
      name: "Create Manifest"
      script: ./create-manifest
